# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7-alpine

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  except:
    - next
