# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7-alpine


build:
  stage: build
  script:
    - python3 setup.py sdist
  artifacts:
    - *.tar.gz


