# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7-alpine

stages:
  - test
  - deploy

before_script:
   - pip install twine
#    - make init
#
# lint:
#   stage: test
#   script:
#     - make lint
#     - make typing

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - python setup.py sdist
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - master@keatontaylor/alexapy
