# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7-alpine

stages:
  - test
  - stage
  - deploy

before_script:
   - pip install twine pipenv-to-requirements
   - apk update
   - apk add --no-cache --update python3-dev gcc build-base make git
   - pipenv_to_requirements
   - pip install -e . -r requirements.txt -r requirements-dev.txt

lint:
  stage: test
  script:
    - "flake8 alexapy"
    - "pydocstyle alexapy"
    - "pylint alexapy"
    - "mypy --ignore-missing-imports alexapy"

bump_and_publish:
  stage: deploy
  variables:
    PYPI_USERNAME: $PRODUCTION_USERNAME
    PYPI_PASSWORD: $PRODUCTION_PASSWORD
    GL_TOKEN: $GL_TOKEN
  script:
    - git config --global user.name "semantic-release (via GitLabCI)"
    - git config --global user.email "semantic-release@GitLabCI"
    - "semantic-release publish"
  artifacts:
    paths:
      - dist
  only:
    - master@keatontaylor/alexapy
