# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7-alpine

stages:
  - test
  - stage
  - deploy

before_script:
   - pip install twine
   - apk update
   - apk add --no-cache --update python3-dev gcc build-base make git
   - make init

lint:
  stage: test
  script:
    - make lint
    - make typing

bump_and_publish:
  stage: deploy
  variables:
    PYPI_USERNAME: $PRODUCTION_USERNAME
    PYPI_PASSWORD: $PRODUCTION_PASSWORD
    GL_TOKEN: $GL_TOKEN
  script:
    - make bump_and_publish
  artifacts:
    paths:
      - dist
  only:
    - master@keatontaylor/alexapy

# deploy_production:
#   stage: deploy
#   variables:
#     TWINE_USERNAME: $PRODUCTION_USERNAME
#     TWINE_PASSWORD: $PRODUCTION_PASSWORD
#   script:
#     - python setup.py sdist
#     - twine upload dist/*
#   artifacts:
#     paths:
#       - dist
#   only:
#     - master@keatontaylor/alexapy
