# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: python:3.7

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $PIP_CACHE_DIR
    - .venv/

stages:
  - test
  - stage
  - deploy

before_script:
  - python -V
  #  - apk update
  #  - apk add --no-cache --update python3-dev gcc build-base make git
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

lint:
  stage: test
  script:
    - make lint

check_vulns:
  stage: test
  script:
    - make check_vulns
  rules:
    - allow_failure: true

bump_and_publish:
  stage: deploy
  variables:
    PYPI_USERNAME: $PRODUCTION_USERNAME
    PYPI_PASSWORD: $PRODUCTION_PASSWORD
    GL_TOKEN: $GL_TOKEN
  script:
    - git config --global user.name "semantic-release (via GitLabCI)"
    - git config --global user.email "semantic-release@GitLabCI"
    - make bump_and_publish
  artifacts:
    paths:
      - dist
  only:
    - master@keatontaylor/alexapy
